[package]
name = "world-chain-builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# reth
reth-primitives = { git = "https://github.com/ewoolsey/reth", rev = "b2848f", features = [
    "reth-codec",
] }
reth-revm = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-cli-util = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-cli = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-node-builder = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-chainspec = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-evm = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-db = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-provider = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-transaction-pool = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-payload-builder = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-network-api = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-node-api = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-rpc = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-rpc-types = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-rpc-eth-api = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-rpc-eth-types = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-tasks = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-network = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-basic-payload-builder = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-execution-types = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-prune-types = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-trie = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-chain-state = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-eth-wire-types = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }

# reth-optimism
reth-evm-optimism = { git = "https://github.com/ewoolsey/reth", rev = "b2848f", features = [
    "optimism",
] }
reth-node-optimism = { git = "https://github.com/ewoolsey/reth", rev = "b2848f", features = [
    "optimism",
] }
reth-optimism-cli = { git = "https://github.com/ewoolsey/reth", rev = "b2848f", features = [
    "optimism",
] }
reth-optimism-rpc = { git = "https://github.com/ewoolsey/reth", rev = "b2848f", features = [
    "optimism",
] }
reth-optimism-consensus = { git = "https://github.com/ewoolsey/reth", rev = "b2848f", features = [
    "optimism",
] }
reth-optimism-chainspec = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-optimism-payload-builder = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }

# alloy
op-alloy-consensus = "0.2"
op-alloy-rpc-types = "0.2"
op-alloy-network = "0.2"
alloy-consensus = "0.3"
alloy-network = "0.3"
alloy-primitives = "0.8"
alloy-rpc-types-eth = "0.3"
alloy-rpc-types = "0.3"
alloy-rlp = "0.3"
alloy-eips = "0.3"

# other
revm = "14"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
chrono = "0.4"
thiserror = "1"
strum = "0.26"
strum_macros = "0.26"
bytemuck = "1"
revm-primitives = { version = "9.0.0", default-features = false, features = [
    "std",
] }
semaphore = { git = "https://github.com/worldcoin/semaphore-rs", rev = "f44b7934", features = [
    "depth_30",
] }
clap = { version = "4", features = ["derive", "env"] }
eyre = { version = "0.6", package = "color-eyre" }
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
parking_lot = "0.12"
derive_more = "1"
dotenvy = "0.15.7"
tikv-jemallocator = { version = "0.6.0", optional = true }

[dev-dependencies]
tempfile = "3"
ethers-core = { git = "https://github.com/gakonst/ethers-rs", default-features = false }
reth-provider = { git = "https://github.com/ewoolsey/reth", rev = "b2848f", features = [
    "test-utils",
] }
alloy-primitives = "0.8"
serde_json = "1"
rand = "0.8"
reth-e2e-test-utils = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-consensus = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-node-core = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
reth-tracing = { git = "https://github.com/ewoolsey/reth", rev = "b2848f" }
alloy-signer-local = "0.3"
[features]
jemalloc = ["tikv-jemallocator"]

[[bin]]
name = "world-chain-builder"
path = "bin/world-chain-builder.rs"
